name: liturgias_diarias_comentadas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  intl: ^0.20.2
  simple_gesture_detector: ^0.2.1
  horizontal_week_calendar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/igreja.jpg

